[versions]
agp = "8.7.0"
appcompat = "1.6.1"
material = "1.12.0"
annotationJvm = "1.9.1"
qmblurview = "1.0.4.5-Beta1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
qmblurview = { module = "com.qmdeve:QmBlurView", version.ref = "qmblurview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }